#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#define MAX_ROWS 5
#define MAX_COLS 8

void scanArray(float [][MAX_COLS], int *, int *);
float sumPartial(float [][MAX_COLS], int, int, int *, int *);

int main(void) {
	float arr[MAX_ROWS][MAX_COLS],
		  sum;  // sum from [0, 0] to random position

	int rows, cols, // actual number of rows and cols, given by user
		x, y; // a random position to be generated by sumPartial function

	scanArray(arr, &rows, &cols);

	// call sumPartial function here
	sum = sumPartial(arr, rows, cols, &x, &y);
	
	printf("Sum to position [%d][%d] = %.2f\n", x, y, sum);

	return 0;
}

// read array size and values of array
// pass back size of array (row, col) through pointers
void scanArray(float arr[][MAX_COLS], 
		int *rowsPtr, int *colsPtr) {
	int r, c;

	printf("Enter rows and columns: ");
	scanf("%d %d", rowsPtr, colsPtr);
	// or scanf("%d %d", &*rowsPtr, &*colsPtr); which is equivalent

	printf("Enter %d values:\n", (*rowsPtr) * (*colsPtr)) ;
	for (r=0; r < *rowsPtr; r++)
		for (c=0; c < *colsPtr; c++)
			scanf("%f", &arr[r][c]);
}

// Generate a random position[x][y] and sum elements from 
// position [0][0] to that position.
// function header is incomplete!
float sumPartial(float arr[][MAX_COLS], int rows, int cols, int *xPtr, int *yPtr) {
	
	int i, j;
	float sum = 0;
	
	srand(time(NULL));
	*xPtr = rand()%(rows);
	*yPtr = rand()%(cols);
	
	for(i=0; i<=*xPtr; i++)
	{
		for(j=0; j<=*yPtr; j++)
		{
			sum += arr[i][j];
		}
	}

	return sum; // stub
}
